# a Dockerfile is like a recipe that tells Docker how to build the imgae 

# what base image to start with
FROM debian:12
# files to copy from host to container
COPY conf/nginx.conf /home/yuwu/42/Inception/srcs/nginx/nginx.conf
# Document which port the container uses (just document!)
EXPOSE 80

RUN

WORKDIR

CMD

ENTRYPOINT