# a Dockerfile is like a recipe that tells Docker how to build the imgae 

# what base image to start with
FROM nginx:alpine
# files to copy from host to container
COPY index.html /home/yuwu/42/Inception/srcs/nginx/index.html/
# Document which port the container uses (just document!)
EXPOSE 80